/*
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>

int main (int argc, char *argv[]) {
	int sum = 0;
	int section[3] = {1,1,2};
	

	while(section[2]<4000000) {
		if(section[2]%2 == 0) {
			sum += section[2];
		}
		section[0] = section[1];
		section[1] = section[2];
		section[2] = section[0]+section[1];
	}

	printf("%d\n", sum);
	return 0;
}
